---
language: cpp

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - deadsnakes
        packages:
            - g++-4.8
            - python3.5
            - python3.5-dev

script:
    - pip install ./setup.py
    - python setup.py test
